apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ingressClass:
      name: traefik
      isDefaultClass: true
    providers:
      kubernetesCRD:
        ingressClass: traefik
      kubernetesIngress:
        ingressClass: traefik
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
    api:
      dashboard: true
    logs:
      general:
        level: INFO
    accessLog:
      format: json
      fields:
        defaultMode: keep
        names:
          ClientAddr: keep
          RequestHost: keep
          RequestMethod: keep
          RequestPath: keep
          RequestProtocol: keep
          DownstreamStatus: keep
          Duration: keep
          RouterName: keep
          ServiceName: keep
        headers:
          defaultMode: drop
          names:
            Authorization: redact
            Cookie: drop
            X-Forwarded-For: keep
            X-Real-Ip: keep
    tracing:
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: opentelemetry-collector.otel.svc.cluster.local:4317
          insecure: true
