apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yml: |
    tunnel: 15057c3d-1da2-4318-90ba-ec23dcc122b9
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - service: https://traefik.kube-system:443
        originRequest:
          noTLSVerify: true
          http2Origin: true
