apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - allowlist-configmap.yaml
  - env-configmap.yaml
  - work-root-pvc.yaml
  - ghcr-pull-externalsecret.yaml
  - externalsecret-runtime.yaml
  - externalsecret-github-app.yaml
  - externalsecret-webhook.yaml
  - eventbus.yaml
  - eventsource.yaml
  - sensor.yaml
  - workflowtemplate.yaml
  - certificate.yaml
  - ingressroute.yaml
