apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yml: |
    tunnel: 837149ae-9c1e-4866-ad48-f7d60aac090a
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - service: https://traefik.kube-system:443
        originRequest:
          noTLSVerify: true
          http2Origin: true
