apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yml: |
    tunnel: 5a7130ae-6f54-4f9d-aa8e-ed879458e05d
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - service: https://traefik.traefik.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
          http2Origin: true
