apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        credentials.json: "{{ .credentialsJson }}"
  data:
    - secretKey: credentialsJson
      remoteRef:
        key: ai-hub-cloudflared
        property: credentials-json
